import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const koulen = localFont({
  src: [
    {
      path: "./fonts/Koulen.ttf",
    },
  ],
  variable: "--koulen",
});

const abel = localFont({
  src: [
    {
      path: "./fonts/Abel/Abel-Regular.ttf",
    },
  ],
  variable: "--abel",
});

const roboto = localFont({
  src: [
    {
      path: "./fonts/Roboto/Roboto-ExtraLight.ttf",
    },
    {
      path: "./fonts/Roboto/Roboto-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/Roboto/Roboto-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/Roboto/Roboto-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Roboto/Roboto-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Roboto/Roboto-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Roboto/Roboto-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${koulen.variable} ${abel.variable} ${roboto.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
