import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const koulen = localFont({
  src: [
    {
      path: "./fonts/Koulen.ttf",
    },
  ],
  variable: "--koulen",
});

const abel = localFont({
  src: [
    {
      path: "./fonts/Abel/Abel-Regular.ttf",
    },
  ],
  variable: "--abel"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${koulen.variable} ${abel.variable}`}>{children}</body>
    </html>
  );
}
